# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-27 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='email',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
