# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-07 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_auto_20181127_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
