# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-07 17:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_auto_20181207_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
