# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-08 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.CharField(max_length=2000),
        ),
    ]
