# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-13 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_auto_20181208_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.CharField(max_length=10000),
        ),
    ]
